Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mahak/studybud_clone/base/views.py", line 78, in home
    return render(request,'base/home.html',context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/db/models/fields/files.py", line 64, in url
    return self.storage.url(self.name)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/storages/backends/s3.py", line 698, in url
    "get_object", Params=params, ExpiresIn=expire, HttpMethod=http_method
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 710, in generate_presigned_url
    operation_name=operation_name,
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 350, in generate_presigned_url
    signing_name,
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/auth.py", line 998, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
"GET / HTTP/1.1" 500 145
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
TypeError: 'ImageFieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mahak/studybud_clone/base/views.py", line 78, in home
    return render(request,'base/home.html',context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 988, in render
    output = self.filter_expression.resolve(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/django/db/models/fields/files.py", line 64, in url
    return self.storage.url(self.name)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/storages/backends/s3.py", line 698, in url
    "get_object", Params=params, ExpiresIn=expire, HttpMethod=http_method
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 710, in generate_presigned_url
    operation_name=operation_name,
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 350, in generate_presigned_url
    signing_name,
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/Users/mahak/studybud/env/lib/python3.7/site-packages/botocore/auth.py", line 998, in add_auth
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
"GET / HTTP/1.1" 500 145
